# Generated by Django 5.2.6 on 2025-10-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="points",
        ),
    ]
