# Generated by Django 5.2.6 on 2025-10-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_team_player_position_lineup_lineupplayer_player_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "logins",
                "ordering": ["username"],
            },
        ),
    ]
