# Generated by Django 5.2.6 on 2025-10-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_savant_batter_stats'),
        ('api', '0003_login'),
    ]

    operations = [
    ]
