# Generated by Django 5.2.6 on 2025-11-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
