"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
import environ

# Paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from the repo root or project root
env = environ.Env()
# Try ../.env first (repo root); fall back to BASE_DIR/.env if needed
env_file_candidates = [BASE_DIR.parent / ".env", BASE_DIR / ".env"]
for _candidate in env_file_candidates:
    if _candidate.exists():
        environ.Env.read_env(_candidate)
        break

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = env("SECRET_KEY", default="dev-only-not-secret")
DEBUG = env.bool("DEBUG", default=True)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "lineups",
    "accounts",
    "roster",
    "simulator",
    "project_tests",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    )
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB", default="appdb"),
        "USER": env("POSTGRES_USER", default="appuser"),
        "PASSWORD": env("POSTGRES_PASSWORD", default="secret"),
        "HOST": env("DB_HOST", default="localhost"),
        "PORT": env("DB_PORT", default="5432"),
        "OPTIONS": {"options": "-c search_path=public"},
    }
}

# If DATABASE_URL is provided (Render does this automatically), use it
# This overrides the above configuration for production
if "DATABASE_URL" in os.environ:
    DATABASES["default"] = dj_database_url.config(
        default=os.environ["DATABASE_URL"],
        conn_max_age=600,
        conn_health_checks=True,
    )

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings
# Allow all origins in development, but restrict in production
CORS_ALLOW_CREDENTIALS = True  # Required for auth cookies/tokens

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # Get frontend origins from environment variable (comma-separated)
    # Example: CORS_ORIGINS=https://frontend.onrender.com,https://custom-domain.com
    cors_origins_env = env("CORS_ORIGINS", default="")

    # Default frontend origins
    CORS_ALLOWED_ORIGINS = [
        "https://bench-analytics.onrender.com",
    ]

    # Add any additional origins from environment variable
    if cors_origins_env:
        additional_origins = [
            o.strip() for o in cors_origins_env.split(",") if o.strip()
        ]
        CORS_ALLOWED_ORIGINS.extend(additional_origins)

    # If you need to allow localhost for testing production builds
    if env.bool("ALLOW_LOCALHOST_CORS", default=False):
        CORS_ALLOWED_ORIGINS.extend(
            [
                "http://localhost:3000",
                "http://127.0.0.1:3000",
            ]
        )
