# Generated by Django 5.2.6 on 2025-10-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    # No-op migration: these Player fields were moved into the `roster` app's
    # initial migration during the refactor. Keep a placeholder migration to
    # preserve historical migration numbering and avoid applying duplicate
    # operations.
    dependencies = [
        ("lineups", "0002_team_player_position_lineup_lineupplayer_player_team"),
    ]

    operations = []
