# Generated by Django 5.2.6 on 2025-10-16 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ("lineups", "0004_merge_0003_add_savant_batter_stats_0003_login"),
]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="lineups.team",
            ),
        ),
    ]
