# Generated by Django 5.2.6 on 2025-10-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lineups", "0003_add_savant_batter_stats"),
        ("lineups", "0004_merge_0003_add_savant_batter_stats_0003_login"),
        ("lineups", "0005_alter_player_team"),
    ]

    operations = []
