# Generated by Django 5.2.6 on 2025-11-03 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineups", "0006_merge_20251029_1936"),
        ("roster", "0002_add_savant_batter_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineupplayer",
            name="batting_order",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="lineupplayer",
            constraint=models.UniqueConstraint(
                fields=("lineup", "player"), name="unique_player_per_lineup"
            ),
        ),
        migrations.AddConstraint(
            model_name="lineupplayer",
            constraint=models.UniqueConstraint(
                fields=("lineup", "batting_order"),
                name="unique_batting_order_per_lineup",
            ),
        ),
    ]
