# Generated by Django 5.2.6 on 2025-11-04 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineups", "0007_alter_lineupplayer_batting_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineupplayer",
            name="batting_order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
            ),
        ),
    ]
