# Generated by Django 5.2.6 on 2025-11-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineups", "0008_alter_lineupplayer_batting_order"),
        ("roster", "0003_remove_player_avg_best_speed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineup",
            name="opponent_pitcher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="roster.player",
            ),
        ),
    ]
