# Generated by Django 5.2.6 on 2025-11-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lineups", "0009_make_opponent_pitcher_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineup",
            name="opponent_pitcher",
        ),
        migrations.RemoveField(
            model_name="lineup",
            name="opponent_team",
        ),
    ]
