# Generated by Django 5.2.6 on 2025-11-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lineups", "0010_remove_lineup_opponent_pitcher_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineupplayer",
            name="position",
        ),
    ]
