/**
 * SabermetricsModePanel - Component for algorithm-based lineup creation
 */

import React from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "../../../ui/components/card";
import { Button } from "../../../ui/components/button";
import PlayersOrderedList from "../../players/components/PlayersOrderedList";

interface SabermetricsModePanelProps {
  lineupPlayers: any[];
  generatedLineup: any[];
  lineupName: string;
  saveStatus: "idle" | "saving" | "saved";
  generating: boolean;
  onPlayerClick: (player: any) => void;
  onLineupNameChange: (name: string) => void;
  onGenerate: () => Promise<void>;
  onSave: () => Promise<void>;
}

export function SabermetricsModePanel({
  lineupPlayers,
  generatedLineup,
  lineupName,
  saveStatus,
  generating,
  onPlayerClick,
  onLineupNameChange,
  onGenerate,
  onSave,
}: SabermetricsModePanelProps) {
  return (
    <div className="grid md:grid-cols-2 gap-6">
      <Card>
        <CardHeader>
          <CardTitle>Algorithm Generator</CardTitle>
          <CardDescription>
            Generate an optimal batting order using sabermetrics
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-sm text-muted-foreground mb-4">
            Use the algorithm to generate an optimal lineup based on player
            statistics.
          </div>
          <div className="pt-4">
            <PlayersOrderedList
              players={lineupPlayers}
              onItemClick={onPlayerClick}
              badgeClassName="bg-gray-400 text-white"
            />
            <div className="pt-4">
              <Button className="w-full" onClick={onGenerate}>
                {generating ? "Generating…" : "Generate Lineup"}
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Generated Lineup</CardTitle>
          <CardDescription>
            Optimal batting order generated by the algorithm
          </CardDescription>
        </CardHeader>
        <CardContent>
          {generatedLineup.length > 0 ? (
            <>
              <PlayersOrderedList
                players={generatedLineup}
                onItemClick={onPlayerClick}
                badgeClassName="bg-primary text-white dark:bg-primary"
              />
              <div className="mt-6 space-y-3">
                <div>
                  <label
                    htmlFor="lineup-name-sabermetrics"
                    className="block text-sm font-medium text-gray-700 mb-1"
                  >
                    Lineup Name
                  </label>
                  <input
                    id="lineup-name-sabermetrics"
                    type="text"
                    value={lineupName}
                    onChange={(e) => onLineupNameChange(e.target.value)}
                    placeholder="Enter lineup name..."
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
                  />
                </div>
                <Button
                  className={`w-full ${
                    saveStatus === "saved"
                      ? "bg-green-600 hover:bg-green-600"
                      : ""
                  } disabled:bg-gray-200 disabled:cursor-not-allowed`}
                  disabled={!lineupName.trim() || saveStatus === "saving"}
                  onClick={onSave}
                >
                  {saveStatus === "saving"
                    ? "Saving..."
                    : saveStatus === "saved"
                    ? "Saved ✓"
                    : "Save Lineup"}
                </Button>
              </div>
            </>
          ) : (
            <div className="text-center text-muted-foreground py-8">
              Click "Generate Lineup" to see the optimal batting order.
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

