# Generated by Django on make migrations

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={"db_table": "teams", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        to="roster.Team",
                        on_delete=models.deletion.CASCADE,
                        related_name="players",
                        null=True,
                        blank=True,
                    ),
                ),
                ("position", models.CharField(default="DH", max_length=3)),
                (
                    "savant_player_id",
                    models.PositiveIntegerField(null=True, blank=True),
                ),
                ("year", models.PositiveIntegerField(null=True, blank=True)),
                ("pa", models.PositiveIntegerField(null=True, blank=True)),
                ("k_percent", models.FloatField(null=True, blank=True)),
                ("bb_percent", models.FloatField(null=True, blank=True)),
                ("woba", models.FloatField(null=True, blank=True)),
                ("xwoba", models.FloatField(null=True, blank=True)),
                ("sweet_spot_percent", models.FloatField(null=True, blank=True)),
                ("barrel_batted_rate", models.FloatField(null=True, blank=True)),
                ("hard_hit_percent", models.FloatField(null=True, blank=True)),
                ("avg_best_speed", models.FloatField(null=True, blank=True)),
                ("avg_hyper_speed", models.FloatField(null=True, blank=True)),
                ("whiff_percent", models.FloatField(null=True, blank=True)),
                ("swing_percent", models.FloatField(null=True, blank=True)),
            ],
            options={"db_table": "players", "ordering": ["name"]},
        ),
    ]
