# Generated by Django 5.2.6 on 2025-10-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    # No-op: these fields were included in roster's 0001_initial during the
    # refactor; keep a placeholder migration to preserve historic ordering.
    dependencies = [
        ("roster", "0001_initial"),
    ]

    operations = []
