# Generated by Django 5.2.6 on 2025-11-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0002_add_savant_batter_stats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="avg_best_speed",
        ),
        migrations.RemoveField(
            model_name="player",
            name="avg_hyper_speed",
        ),
        migrations.RemoveField(
            model_name="player",
            name="sweet_spot_percent",
        ),
        migrations.RemoveField(
            model_name="player",
            name="swing_percent",
        ),
        migrations.RemoveField(
            model_name="player",
            name="whiff_percent",
        ),
        migrations.AddField(
            model_name="player",
            name="home_run",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="isolated_power",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="on_base_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="r_total_stolen_base",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="slg_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="sprint_speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
