# Generated by Django 5.2.6 on 2025-11-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0003_remove_player_avg_best_speed_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="team",
            name="name",
        ),
    ]
