# Generated by Django 5.2.6 on 2025-11-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0004_alter_team_options_remove_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="strikeout",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="home_run",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
