# Generated by Django 5.2.6 on 2025-11-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_alter_team_options_remove_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='b_game',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
