# Generated by Django 5.2.6 on 2025-11-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_player_b_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='b_hit_by_pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='double',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='single',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='triple',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='walk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
