# Generated by Django 5.2.6 on 2025-11-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_player_b_hit_by_pitch_player_double_player_hit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ab',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='b_gnd_into_dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='b_intent_walk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='b_sac_fly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='b_total_bases',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='b_total_sacrifices',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='r_total_caught_stealing',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
