# Generated by Django 5.2.6 on 2025-11-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_player_ab_player_b_gnd_into_dp_player_b_intent_walk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='b_total_sacrifices',
            new_name='b_sac_bunt',
        ),
        migrations.RemoveField(
            model_name='player',
            name='barrel_batted_rate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hard_hit_percent',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sprint_speed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='woba',
        ),
        migrations.RemoveField(
            model_name='player',
            name='xwoba',
        ),
    ]
