# Generated by Django 5.2.6 on 2025-11-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0005_player_double_player_hit_player_strikeout_and_more"),
        ("roster", "0007_player_ab_player_b_gnd_into_dp_player_b_intent_walk_and_more"),
    ]

    operations = [
        # This is an empty merge migration created to combine two divergent migration
        # branches. No schema operations are required here; Django will consider the
        # migration graph linear after applying this.
    ]
