# Generated by Django 5.2.6 on 2025-11-18 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0008_merge_0005_and_0007"),
        ("roster", "0008_rename_b_total_sacrifices_player_b_sac_bunt_and_more"),
    ]

    operations = [
        # Empty merge migration to join two 0008 leaf nodes into a single linear graph.
    ]
