# Generated by Django 5.2.6 on 2025-11-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0008_rename_b_total_sacrifices_player_b_sac_bunt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="position",
        ),
    ]
