# Generated by Django 5.2.6 on 2025-11-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0009_merge_0008s"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="position",
        ),
    ]
