# Generated by Django 5.2.6 on 2025-12-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0009_remove_player_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="barrel_batted_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="xwoba",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
